In [5]:
import numpy as np
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [2]:
my_list = [1,2,3,4]

NameError: name 'my_list' is not defined

In [1]:
np.array(my_list)


NameError: name 'np' is not defined

In [6]:
my_math = [[1,2,3],[3,4,5],[6,7,8]]
np.array(my_math)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [2]:
np.random.rand(5)

NameError: name 'np' is not defined

In [1]:
np.eye(4)

NameError: name 'np' is not defined

In [2]:
import numpy as np
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.random.rand(5)

array([0.11096963, 0.78896501, 0.50786585, 0.10151409, 0.72612141])

In [4]:
np.random.rand(5,5)

array([[0.08626699, 0.31618807, 0.49911261, 0.53630173, 0.60793612],
       [0.18458402, 0.14232759, 0.62011997, 0.93370413, 0.59725406],
       [0.37774974, 0.8625474 , 0.4475669 , 0.90713022, 0.67612917],
       [0.86566824, 0.89956125, 0.25169816, 0.61538332, 0.26609772],
       [0.22405355, 0.66065891, 0.23068562, 0.70921486, 0.06067599]])

In [9]:
np.random.randint(1,100)  # This will return random integer number between 1 and 100

14

In [10]:
np.random.randint(1,100,10)     # this will return 10 integer numbers between 1 and 100 

array([38, 52, 11, 16, 27, 43, 26,  2, 15, 27])

In [11]:
arr = np.arange(25)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
arr.reshape(5,5)              # Since "arr" has only 25 members from 0 to 24 then here parameters should be 5 * 5 not 5 * 10 , otherwise this will through an error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr.max()

24

In [17]:
arr.argmax()        # This will return the index number of largest value 

24

In [18]:
arr.dtype

dtype('int32')